### ISSUE TITLE
Can you open-source your code?

### ISSUE THREAD

**Issue by zezixi** [ZszYmy9/Puff-Net#4]
I would like to see the results of the comparison model. If you have time, could you please post your code? thank you.

**Comment by ZszYmy9** [comment]
Our code is released now.

**Comment by zezixi** [comment]
Thank you，But I don't know how to install extraction2, can you please tell me? Thank you again.

**Comment by zezixi** [comment]
Thank you，But I don't know how to install extraction2, can you please tell me? Thank you again.

**Comment by ZszYmy9** [comment]
Sorry about that. Extraction2 was used in our experiment and it has been corrected now.&nbsp;

**Comment by zezixi** [comment]
Thank you. I have another question. How much VRAM does your code require when B=1, and my 3090 can't run it?
